-- MentalCream v2 fresh Oracle schema
-- 신규/빈 스키마에서만 실행한다. 기존 테이블을 삭제하거나 덮어쓰지 않는다.

CREATE TABLE app_user (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50 CHAR) NOT NULL,
    password_hash VARCHAR2(100 CHAR) NOT NULL,
    display_name VARCHAR2(50 CHAR) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uk_app_user_username UNIQUE (username)
);

CREATE TABLE daily_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    log_date DATE NOT NULL,
    mood NUMBER(1),
    energy NUMBER(1),
    worry_text VARCHAR2(200 CHAR),
    worry_intensity NUMBER(1) DEFAULT 0,
    note VARCHAR2(500 CHAR),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_daily_log_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT uk_daily_log_user_date UNIQUE (user_id, log_date)
);

CREATE TABLE done_item (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_log_id NUMBER NOT NULL,
    category VARCHAR2(255 CHAR) NOT NULL,
    title VARCHAR2(120 CHAR) NOT NULL,
    minutes NUMBER,
    intensity NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_done_item_daily_log FOREIGN KEY (daily_log_id) REFERENCES daily_log(id),
    CONSTRAINT ck_done_item_category CHECK (category IN ('STUDY', 'RUN', 'PROJECT', 'LIFE'))
);

CREATE INDEX idx_done_item_daily_log ON done_item(daily_log_id);

CREATE TABLE suggestion (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    log_date DATE NOT NULL,
    category VARCHAR2(255 CHAR) NOT NULL,
    title VARCHAR2(120 CHAR) NOT NULL,
    minutes NUMBER,
    reason VARCHAR2(1000 CHAR),
    recovery_flag NUMBER(1) DEFAULT 0 NOT NULL,
    confidence_score NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_suggestion_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT uk_suggestion_user_date UNIQUE (user_id, log_date),
    CONSTRAINT ck_suggestion_category CHECK (category IN ('STUDY', 'RUN', 'PROJECT', 'LIFE')),
    CONSTRAINT ck_suggestion_recovery CHECK (recovery_flag IN (0, 1))
);
